CREATE TABLE app_users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    middlename VARCHAR(50),
    surname VARCHAR(50) NOT NULL,
    email VARCHAR(30) UNIQUE,
    password VARCHAR(60) NOT NULL,
    credentialExpired TIMESTAMP WITH TIME ZONE,
    status VARCHAR(40),
    created_at TIMESTAMP WITH TIME ZONE default current_timestamp,
    update_at  TIMESTAMP WITH TIME ZONE default current_timestamp,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
